# Imports 
import pandas as pd                               # DataFrame library: loads/manipulates the CSVs as tables
import numpy as np                                 # Numeric library: linspace, infinity, array math
import matplotlib                                  # The base plotting library
matplotlib.use("Agg")                              # Render to image files instead of opening a screen window
                                                    # (required in headless/server environments with no display)
import matplotlib.pyplot as plt                    # The plotting interface we call directly (plt.plot, plt.savefig...)
from matplotlib.path import Path                   # Lets us define custom curved shapes (used for the chord diagram)
import matplotlib.patches as patches               # Lets us draw those custom shapes onto a plot (PathPatch)
from mpl_toolkits.mplot3d import Axes3D            # Registers the "3d" projection type with matplotlib

import networkx as nx                              # Graph library: builds the substation network and computes its layout
import warnings                                    # Standard library: lets us control which warnings get shown
warnings.filterwarnings("ignore")                  # Suppress noisy deprecation/future warnings so output stays readable

# A single shared color palette, reused across every chart so the whole gallery looks consistent.
PALETTE = {
    "primary": "#2E86AB", "secondary": "#A23B72", "accent": "#F18F01",
    "danger": "#C73E1D", "neutral": "#6c757d",
}
# Maps each voltage level (in kV) to a fixed color, so voltage always means the same color everywhere.
VOLTAGE_COLORS = {11: "#2ecc71", 33: "#f1c40f", 69: "#e67e22", 161: "#e74c3c", 330: "#8e44ad"}

# Load the three source CSVs 
substations = pd.read_csv("substations.csv")       # One row per substation: id, name, region, lat/lon, voltage...
lines = pd.read_csv("lines.csv")                   # One row per line: source id, destination id, length, status...
utilities = pd.read_csv("utilities.csv")           # One row per utility company (ECG, GRIDCo, VRA, etc.)

# .set_index("Substation ID") makes the ID column the row label instead of a plain column.
# This lets us later write sub_lookup.loc[some_id] to instantly grab that substation's data.
sub_lookup = substations.set_index("Substation ID")

# SECTION 1: GRID EXPANSION SNAPSHOTS (small multiples instead of animation)
print("Building grid expansion snapshot grid...")

# Round the earliest commissioning year DOWN to the nearest 10 (e.g. 1965 -> 1960) for a clean starting point.
# // is integer (floor) division, so (1965 // 10) * 10 == 1960.
min_year = int((substations["Commissioning Year"].min() // 10) * 10)
max_year = int(substations["Commissioning Year"].max())      # The most recent commissioning year, unrounded

# np.linspace(a, b, 4) creates 4 evenly-spaced numbers between a and b (inclusive of both ends).
# .astype(int) rounds each of those 4 numbers down to a whole year, giving us 4 snapshot years to plot.
snapshot_years = np.linspace(min_year, max_year, 4).astype(int)

# Create a figure with 1 row of 4 subplots side by side, 20x5.5 inches total.
# sharex=True/sharey=True means all 4 panels use the same axis scale, so they're visually comparable.
fig, axes = plt.subplots(1, 4, figsize=(20, 5.5), sharex=True, sharey=True)

# zip(axes, snapshot_years) pairs each of the 4 subplot axes with one of the 4 snapshot years,
# so the loop body runs once per panel.
for ax, snap_year in zip(axes, snapshot_years):
    # Keep only substations that existed by this snapshot year (cumulative, not just "built in that year")
    built = substations[substations["Commissioning Year"] <= snap_year]
    # .map(VOLTAGE_COLORS) converts each substation's voltage number into its matching hex color string
    colors = built["Voltage (kV)"].map(VOLTAGE_COLORS)
    ax.scatter(built["Longitude"], built["Latitude"], c=colors,
               s=built["Capacity (MVA)"], alpha=0.8, edgecolors="black", linewidths=0.3)
    # s=... sets each dot's SIZE proportional to that substation's capacity (bigger capacity = bigger dot)
    ax.set_title(f"By {snap_year}\n({len(built)} substations built)")   # len(built) = how many rows in this snapshot
    ax.set_xlabel("Longitude")
axes[0].set_ylabel("Latitude")                      # Only label the y-axis once, on the leftmost panel

# Build a manual legend: one small circular marker per voltage level, matching the color scheme above.
# This is a common matplotlib trick when a chart's colors come from a manual mapping (not automatically
# generated by a single plot call), so there's no automatic legend to fall back on.
legend_handles = [plt.Line2D([0], [0], marker="o", color="w", markerfacecolor=c, markersize=9, label=f"{v} kV")
                   for v, c in VOLTAGE_COLORS.items()]
# Draw that legend once, centered above the whole figure (not tied to any one subplot).
fig.legend(handles=legend_handles, loc="upper center", ncol=5, bbox_to_anchor=(0.5, 1.08), title="Voltage Level")
fig.suptitle("Grid Expansion Over Time (cumulative substations commissioned)", y=1.15, fontsize=13)
plt.tight_layout()                                  # Auto-adjust spacing so titles/labels don't overlap
plt.savefig("grid_expansion_snapshots.png", dpi=120, bbox_inches="tight")
# bbox_inches="tight" trims any extra whitespace around the figure (important here since our legend/title
# sit ABOVE the normal plot area using y > 1, which could otherwise get cut off).
plt.close()                                         # Free this figure from memory before starting the next one
print("Saved grid_expansion_snapshots.png")

# SECTION 2: STATIC 3D NETWORK VISUALIZATION
print("Building static 3D network plot...")

# Build a graph: one node per substation NAME, one edge per line connecting two substations.
# edge_attr=[...] attaches the Length/Voltage columns as extra data on each edge (not used for drawing here,
# but available if we wanted to e.g. color edges by voltage later).
G = nx.from_pandas_edgelist(
    lines, source="Source Substation", target="Destination Substation",
    edge_attr=["Length (km)", "Voltage (kV)"], create_using=nx.Graph())

# spring_layout simulates nodes as physical objects that repel each other while edges act like springs
# pulling connected nodes together -- this naturally produces a "force-directed" layout.
# dim=3 asks for 3D coordinates (x, y, z) instead of the usual 2D (x, y).
# seed=42 makes the random layout reproducible (same result every run).
# k=0.4 controls the ideal spacing between nodes (higher k = more spread out).
pos_3d = nx.spring_layout(G, dim=3, seed=42, k=0.4)
# pos_3d is now a dictionary: {substation_name: (x, y, z), ...}

# Build a lookup from substation NAME to its Region, so we can color each node by region.
name_to_region = substations.set_index("Name")["Region"].to_dict()
regions_list = sorted(substations["Region"].unique())     # All distinct region names, alphabetically sorted

# plt.get_cmap("tab20") gives us a ready-made palette of 20 distinct colors, good for categorical data.
cmap = plt.get_cmap("tab20")
# Build a dictionary mapping each region to one color from that palette, spread evenly across it.
# i / max(len(regions_list) - 1, 1) turns the region's position (0, 1, 2, ...) into a fraction from 0 to 1,
# which is what get_cmap's colormap objects expect as input. max(..., 1) avoids a divide-by-zero if there's
# only one region.
region_color_map = {r: cmap(i / max(len(regions_list) - 1, 1)) for i, r in enumerate(regions_list)}

fig = plt.figure(figsize=(11, 10))                  # A fresh, roughly-square figure
ax = fig.add_subplot(111, projection="3d")          # Add a single 3D subplot filling the whole figure
                                                     # ("111" means "1 row, 1 column, 1st subplot")

# Draw every edge (line) FIRST, so that node markers get drawn on top of them afterward (better visibility).
for u, v in G.edges():                              # u, v = the two substation names connected by this edge
    x0, y0, z0 = pos_3d[u]                           # 3D coordinates of the first endpoint
    x1, y1, z1 = pos_3d[v]                           # 3D coordinates of the second endpoint
    ax.plot([x0, x1], [y0, y1], [z0, z1], color="lightgray", linewidth=0.7, alpha=0.6)
    # ax.plot with 3D axes draws a straight line segment between the two 3D points

# Build parallel lists of x, y, z coordinates -- one entry per node, in the same order as G.nodes()
xs = [pos_3d[n][0] for n in G.nodes()]
ys = [pos_3d[n][1] for n in G.nodes()]
zs = [pos_3d[n][2] for n in G.nodes()]
# Marker size scales with degree (number of connections): busier hubs get bigger dots.
sizes = [40 + 15 * G.degree(n) for n in G.nodes()]
# Look up each node's region color; fall back to solid gray (0.5, 0.5, 0.5, 1) if the region isn't found.
colors = [region_color_map.get(name_to_region.get(n, ""), (0.5, 0.5, 0.5, 1)) for n in G.nodes()]

# Scatter-plot all nodes in 3D at once (much faster than looping and adding one marker at a time).
ax.scatter(xs, ys, zs, s=sizes, c=colors, edgecolors="black", linewidths=0.4, depthshade=True)
# depthshade=True slightly dims markers that are "further away" in the 3D view, giving a subtle depth cue.

ax.set_title("3D Force-Directed Network of the National Grid\n(node size = number of connections, color = region)")
ax.set_xticks([]); ax.set_yticks([]); ax.set_zticks([])   # Hide axis tick numbers -- spring_layout coordinates
                                                            # are arbitrary and carry no real-world meaning
plt.tight_layout()
plt.savefig("network_3d.png", dpi=120)
plt.close()
print("Saved network_3d.png")

# SECTION 3: STATIC CHORD-STYLE DIAGRAM: inter-regional power-line flows
print("Building static chord diagram...")

lines_regioned = lines.copy()                       # Work on a copy so we don't modify the original `lines` DataFrame
# .map(sub_lookup["Region"]) looks up each line's source/destination substation ID in sub_lookup's Region column
# and attaches the result as a new column -- effectively a fast row-by-row lookup.
lines_regioned["Source Region"] = lines_regioned["Source Substation ID"].map(sub_lookup["Region"])
lines_regioned["Dest Region"] = lines_regioned["Destination Substation ID"].map(sub_lookup["Region"])

flow_counts = {}                                     # Will map (region_a, region_b) -> number of lines between them
for _, row in lines_regioned.iterrows():             # Loop over every line row
    # sorted([...]) ensures (Ashanti, Volta) and (Volta, Ashanti) count as the SAME pair (order doesn't matter)
    pair = tuple(sorted([row["Source Region"], row["Dest Region"]]))
    flow_counts[pair] = flow_counts.get(pair, 0) + 1  # .get(pair, 0) returns 0 if this pair hasn't been seen yet

# Collect every unique region name that appears in any pair, and sort them for a consistent circle ordering.
regions = sorted(set(r for pair in flow_counts for r in pair))
n = len(regions)                                     # How many regions we need to place around the circle
angle_step = 2 * np.pi / n                           # Divide the full circle (2*pi radians = 360 degrees) evenly
# Give each region a fixed angular position around the circle, e.g. region 0 at angle 0, region 1 at angle_step, etc.
region_angle = {r: i * angle_step for i, r in enumerate(regions)}
region_color = {r: cmap(i / max(n - 1, 1)) for i, r in enumerate(regions)}   # Reuse the same tab20 colormap


def circle_point(angle, radius=1.0):
    # Standard trigonometry: convert an angle (in radians) into (x, y) coordinates on a circle of given radius.
    return radius * np.cos(angle), radius * np.sin(angle)


fig, ax = plt.subplots(figsize=(9, 9))               # A square figure, since we're drawing a circle
max_flow = max(flow_counts.values())                 # The single largest flow count, used to normalize line widths

# Draw one curved arc per region PAIR that has at least one connecting line.
for (r1, r2), count in flow_counts.items():
    x0, y0 = circle_point(region_angle[r1])          # Starting point: region r1's position on the circle
    x1, y1 = circle_point(region_angle[r2])          # Ending point: region r2's position on the circle
    # A quadratic Bezier curve needs 3 points: start, a "control point" that pulls the curve's shape, and end.
    # Using (0, 0) -- the circle's center -- as the control point makes every arc sweep inward toward the middle,
    # which is the classic visual signature of a chord diagram.
    verts = [(x0, y0), (0, 0), (x1, y1)]
    codes = [Path.MOVETO, Path.CURVE3, Path.CURVE3]
    # MOVETO = "start the path here"; CURVE3 (used twice) = "this is a quadratic Bezier curve segment"
    path = Path(verts, codes)                         # Combine the points and instructions into a drawable Path
    patch = patches.PathPatch(path, facecolor="none", edgecolor=region_color[r1],
                               linewidth=1 + 6 * count / max_flow, alpha=0.45)
    # facecolor="none" means we only draw the curve's outline, not a filled shape.
    # linewidth scales from 1 (weakest connection) up toward 7 (strongest, i.e. count == max_flow).
    ax.add_patch(patch)                               # Actually draw this arc onto the plot

# Draw a marker + text label for every region, positioned slightly outside the circle (radius=1.03)
for r in regions:
    x, y = circle_point(region_angle[r], radius=1.03)
    ax.scatter([x], [y], s=140, color=[region_color[r]], edgecolors="black", linewidths=0.8, zorder=5)
    # zorder=5 makes sure these markers are drawn ON TOP of the arcs (higher zorder = drawn later/on top)
    ax.text(x * 1.13, y * 1.13, r, ha="center", va="center", fontsize=8)
    # Push the text label a bit further out than the marker itself (radius factor 1.13 vs 1.03) so it doesn't
    # overlap the dot; ha/va center the text horizontally/vertically on that point.

ax.set_xlim(-1.4, 1.4)                                # Fix the visible x-range so all labels fit inside the frame
ax.set_ylim(-1.4, 1.4)                                # Same for y-range
ax.set_aspect("equal")                                # Force equal scaling on both axes so the circle isn't stretched
ax.axis("off")                                        # Hide the axis box, ticks, and numbers entirely (pure diagram)
ax.set_title("Inter-Regional Transmission Line Flows (chord-style diagram)\n(arc thickness = number of connecting lines)")
plt.tight_layout()
plt.savefig("chord_diagram_regional_flows.png", dpi=120)
plt.close()
print("Saved chord_diagram_regional_flows.png")

# SECTION 4: HEATMAP - line density and maintenance-status concentration
print("Building line density / maintenance-status heatmap...")

fig, axes = plt.subplots(1, 2, figsize=(15, 6))       # Two side-by-side panels

# Define length category boundaries: 0-20km, 20-60km, 60km-infinity
bins = [0, 20, 60, np.inf]
dist_labels = ["Short (<20km)", "Medium (20-60km)", "Long (>60km)"]
# pd.cut slices the numeric Length column into these 3 labeled buckets, creating a new categorical column
lines_regioned["Distance Category"] = pd.cut(lines_regioned["Length (km)"], bins=bins, labels=dist_labels)

# pd.crosstab builds a 2D frequency table: rows = Source Region, columns = Distance Category,
# cell values = how many lines fall into that (region, category) combination.
density_matrix = pd.crosstab(lines_regioned["Source Region"], lines_regioned["Distance Category"])

# imshow renders a 2D array as a colored grid of cells ("image show") -- this is the actual heatmap.
im0 = axes[0].imshow(density_matrix.values, cmap="YlOrRd", aspect="auto")
# cmap="YlOrRd" = yellow-orange-red colormap (low values yellow, high values dark red)
# aspect="auto" lets cell width/height stretch to fill the panel instead of forcing square cells

axes[0].set_xticks(range(len(density_matrix.columns)))            # One tick per distance-category column
axes[0].set_xticklabels(density_matrix.columns, rotation=30, ha="right")  # Label ticks with category names, angled
axes[0].set_yticks(range(len(density_matrix.index)))               # One tick per region row
axes[0].set_yticklabels(density_matrix.index)                      # Label ticks with region names
axes[0].set_title("Line Density by Region and Distance Category")
# Loop over every cell in the matrix and print its number directly on top of the colored square
for i in range(density_matrix.shape[0]):              # shape[0] = number of rows (regions)
    for j in range(density_matrix.shape[1]):          # shape[1] = number of columns (distance categories)
        axes[0].text(j, i, density_matrix.values[i, j], ha="center", va="center", fontsize=8)
plt.colorbar(im0, ax=axes[0], label="Line Count")      # Add a color-scale legend bar next to this panel

# Same pattern again, but this time cross-tabulating Region against line Status (Active / Under Maintenance)
status_matrix = pd.crosstab(lines_regioned["Source Region"], lines_regioned["Status"])
im1 = axes[1].imshow(status_matrix.values, cmap="Reds", aspect="auto")
axes[1].set_xticks(range(len(status_matrix.columns)))
axes[1].set_xticklabels(status_matrix.columns, rotation=30, ha="right")
axes[1].set_yticks(range(len(status_matrix.index)))
axes[1].set_yticklabels(status_matrix.index)
axes[1].set_title("Maintenance-Status Concentration by Region")
for i in range(status_matrix.shape[0]):
    for j in range(status_matrix.shape[1]):
        axes[1].text(j, i, status_matrix.values[i, j], ha="center", va="center", fontsize=8)
plt.colorbar(im1, ax=axes[1], label="Line Count")

plt.tight_layout()
plt.savefig("line_density_maintenance_heatmap.png", dpi=120)
plt.close()
print("Saved line_density_maintenance_heatmap.png")

# SECTION 5: STATIC COMPARATIVE CHARTS -- utility infrastructure footprint
print("Building utility comparison charts...")

# Attach each line's utility Code/Type by matching Utility ID between the two tables.
lines_u = lines.merge(utilities[["Utility ID", "Code", "Type"]], on="Utility ID", how="left")

# .value_counts() tallies how many lines belong to each utility Code; .sort_index() orders them alphabetically
line_count_by_utility = lines_u["Code"].value_counts().sort_index()
# .groupby("Code")[...].sum()/.mean() computes the requested statistic PER utility
total_capacity_by_utility = lines_u.groupby("Code")["Capacity (MVA)"].sum().sort_index()
total_length_by_utility = lines_u.groupby("Code")["Length (km)"].sum().sort_index()
avg_length_by_utility = lines_u.groupby("Code")["Length (km)"].mean().round(1).sort_index()

fig, axes = plt.subplots(2, 2, figsize=(13, 9))        # A 2x2 grid of subplots (4 charts total)

# Each of these Series objects has a built-in .plot(kind="bar") shortcut that draws directly onto the given axis.
line_count_by_utility.plot(kind="bar", ax=axes[0, 0], color=PALETTE["primary"], title="Lines Operated per Utility")
axes[0, 0].set_ylabel("Line Count")
total_capacity_by_utility.plot(kind="bar", ax=axes[0, 1], color=PALETTE["secondary"], title="Total Line Capacity (MVA)")
axes[0, 1].set_ylabel("MVA")
total_length_by_utility.plot(kind="bar", ax=axes[1, 0], color=PALETTE["accent"], title="Total Network Length (km)")
axes[1, 0].set_ylabel("km")
avg_length_by_utility.plot(kind="bar", ax=axes[1, 1], color=PALETTE["danger"], title="Average Line Length (km)")
axes[1, 1].set_ylabel("km")

# axes.flat lets us loop over all 4 subplot axes regardless of their (row, column) grid shape
for ax in axes.flat:
    ax.set_xlabel("Utility")
    ax.tick_params(axis="x", rotation=0)               # Keep utility-code labels horizontal (not angled) since they're short

fig.suptitle("Comparative Infrastructure Footprint by Utility", fontsize=13)
plt.tight_layout()
plt.savefig("utility_comparison_charts.png", dpi=120)
plt.close()
print("Saved utility_comparison_charts.png")

print("\nTask 3.2 static visualization gallery complete (all outputs are .png).")
